name: Front-end deploy
on:
  pull_request:
    branches: [main]
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - run: |
            REGEX_ISSUE_ID="^(DRDC-[0-9]+|Merge|hotfix)"
            BRANCH_NAME=$(git symbolic-ref --short HEAD)
            ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
            if [[ -z "$ISSUE_ID" ]]; then
                echo "[commit-msg-hook] Your commit message is illegal. Please rename your branch with using following regex: $REGEX_ISSUE_ID"
                exit 1
            fi